name: Sputter CI Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
      - ".github/workflows/docs.yml"
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
      - ".github/workflows/docs.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 #otherwise MinVer shits itself
          submodules: true #only the docs needs recursive
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run the Cake script
        uses: cake-build/cake-action@v2
        with:
          cake-version: tool-manifest
          target: Release
          arguments: |
            tag-latest: true
        env:
          QUAY_TOKEN: ${{secrets.QUAY_TOKEN}}
          QUAY_USER: sputter+sputter_build
          NUGET_TOKEN: ${{secrets.NUGET_TOKEN}}
      - uses: actions/upload-artifact@v4
        name: Upload Server
        with:
          name: sputter-server
          path: dist/archive/sputter-server-*
      - uses: actions/upload-artifact@v4
        name: Upload CLI
        with:
          name: sputter-cli
          path: |
            dist/publish/Sputter.Console/
            !dist/publish/Sputter.Console/dotnet-any/
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/archive/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}