name: Docs CI Build

on:
  push:
    branches: [ main ]
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout recursively
      uses: actions/checkout@v4
      with:
        submodules: recursive  # Fetch Hugo themes
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    # - name: Use Node.js 20.x
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: 20.x
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.123.0'
        extended: true
    # - run: npm install
    #   working-directory: './docs'
    - name: Build docs
      run: hugo --minify
      working-directory: './docs'
      env:
        HUGO_ENV: production
    - name: Upload docs packages
      uses: actions/upload-artifact@v4
      with:
        name: sputter-docs
        path: docs/public/
    - name: Deploy to Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/public